// <auto-generated />
using System;
using AiPersona.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiPersona.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223051046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiPersona.Domain.Entities.AutomatedResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Keywords")
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("i_x_automated_responses_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_automated_responses_is_active");

                    b.HasIndex("Priority")
                        .HasDatabaseName("i_x_automated_responses_priority");

                    b.ToTable("automated_responses");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message_type");

                    b.Property<string>("MetaData")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_data");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sender_type");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sentiment");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_chat_messages_created_at");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("i_x_chat_messages_session_id_created_at");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeletedPersonaImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_persona_image");

                    b.Property<string>("DeletedPersonaName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deleted_persona_name");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("message_count");

                    b.Property<string>("MetaData")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_data");

                    b.Property<DateTime?>("PersonaDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("persona_deleted_at");

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<string>("PersonaName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("persona_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_chat_sessions_last_message_at");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("i_x_chat_sessions_persona_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("i_x_chat_sessions_user_id_status");

                    b.HasIndex("UserId", "IsPinned", "LastMessageAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("i_x_chat_sessions_user_id_is_pinned_last_message_at");

                    b.ToTable("chat_sessions");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.ContentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additional_info");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("i_x_content_reports_content_id");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("i_x_content_reports_content_type");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_content_reports_created_at");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("i_x_content_reports_reporter_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_content_reports_status");

                    b.ToTable("content_reports");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.FcmToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("i_x_fcm_tokens_device_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_fcm_tokens_is_active");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("i_x_fcm_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_fcm_tokens_user_id");

                    b.ToTable("fcm_tokens");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<string>("MetaData")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_data");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<string>("SourceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("Tokens")
                        .HasColumnType("integer")
                        .HasColumnName("tokens");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("i_x_knowledge_bases_persona_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_knowledge_bases_status");

                    b.ToTable("knowledge_bases");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.MarketplacePersona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("PricingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pricing_type");

                    b.Property<int>("PurchaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("purchase_count");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("i_x_marketplace_personas_category");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("i_x_marketplace_personas_persona_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("i_x_marketplace_personas_seller_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_marketplace_personas_status");

                    b.ToTable("marketplace_personas");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.MarketplacePurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("MarketplacePersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("marketplace_persona_id");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("i_x_marketplace_purchases_buyer_id");

                    b.HasIndex("MarketplacePersonaId")
                        .HasDatabaseName("i_x_marketplace_purchases_marketplace_persona_id");

                    b.HasIndex("PurchasedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_marketplace_purchases_purchased_at");

                    b.ToTable("marketplace_purchases");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.MarketplaceReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MarketplacePersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("marketplace_persona_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text")
                        .HasColumnName("review_text");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MarketplacePersonaId")
                        .HasDatabaseName("i_x_marketplace_reviews_marketplace_persona_id");

                    b.HasIndex("Rating")
                        .HasDatabaseName("i_x_marketplace_reviews_rating");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("i_x_marketplace_reviews_reviewer_id");

                    b.HasIndex("MarketplacePersonaId", "ReviewerId")
                        .IsUnique()
                        .HasDatabaseName("i_x_marketplace_reviews_marketplace_persona_id_reviewer_id");

                    b.ToTable("marketplace_reviews");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.MessageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attachment_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("i_x_message_attachments_message_id");

                    b.ToTable("message_attachments");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<int>("CloneCount")
                        .HasColumnType("integer")
                        .HasColumnName("clone_count");

                    b.Property<Guid?>("ClonedFromPersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloned_from_persona_id");

                    b.Property<int>("ConversationCount")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string>("Expertise")
                        .HasColumnType("jsonb")
                        .HasColumnName("expertise");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsMarketplace")
                        .HasColumnType("boolean")
                        .HasColumnName("is_marketplace");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("LanguageStyle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("language_style");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("like_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OriginalCreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_creator_id");

                    b.PrimitiveCollection<string>("PersonalityTraits")
                        .HasColumnType("jsonb")
                        .HasColumnName("personality_traits");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voice_id");

                    b.Property<string>("VoiceSettings")
                        .HasColumnType("text")
                        .HasColumnName("voice_settings");

                    b.HasKey("Id");

                    b.HasIndex("ClonedFromPersonaId")
                        .HasDatabaseName("i_x_personas_cloned_from_persona_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_personas_created_at");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("i_x_personas_creator_id");

                    b.HasIndex("IsMarketplace")
                        .HasDatabaseName("i_x_personas_is_marketplace");

                    b.HasIndex("LikeCount")
                        .IsDescending()
                        .HasDatabaseName("i_x_personas_like_count");

                    b.HasIndex("OriginalCreatorId")
                        .HasDatabaseName("i_x_personas_original_creator_id");

                    b.HasIndex("IsPublic", "Status")
                        .HasDatabaseName("i_x_personas_is_public_status");

                    b.ToTable("personas");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.PersonaFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("i_x_persona_favorites_persona_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_persona_favorites_user_id");

                    b.HasIndex("UserId", "PersonaId")
                        .IsUnique()
                        .HasDatabaseName("i_x_persona_favorites_user_id_persona_id");

                    b.ToTable("persona_favorites");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.PersonaLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("i_x_persona_likes_persona_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_persona_likes_user_id");

                    b.HasIndex("UserId", "PersonaId")
                        .IsUnique()
                        .HasDatabaseName("i_x_persona_likes_user_id_persona_id");

                    b.ToTable("persona_likes");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.PersonaView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("i_x_persona_views_persona_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_persona_views_user_id");

                    b.HasIndex("ViewedAt")
                        .HasDatabaseName("i_x_persona_views_viewed_at");

                    b.ToTable("persona_views");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.SubscriptionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_id");

                    b.Property<string>("PurchaseToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purchase_token");

                    b.Property<string>("RawResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_response");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subscription_tier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_subscription_events_created_at");

                    b.HasIndex("PurchaseToken")
                        .HasDatabaseName("i_x_subscription_events_purchase_token");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("i_x_subscription_events_user_id_created_at");

                    b.ToTable("subscription_events");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("i_x_support_tickets_assigned_to");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_support_tickets_created_at");

                    b.HasIndex("Priority")
                        .HasDatabaseName("i_x_support_tickets_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_support_tickets_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_support_tickets_user_id");

                    b.ToTable("support_tickets");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.SupportTicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attachments")
                        .HasColumnType("jsonb")
                        .HasColumnName("attachments");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsStaffReply")
                        .HasColumnType("boolean")
                        .HasColumnName("is_staff_reply");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_support_ticket_messages_created_at");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("i_x_support_ticket_messages_sender_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("i_x_support_ticket_messages_ticket_id");

                    b.ToTable("support_ticket_messages");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_name");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("i_x_uploaded_files_category");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_uploaded_files_user_id");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("i_x_uploaded_files_reference_type_reference_id");

                    b.ToTable("uploaded_files");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UsageTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GeminiApiCallsToday")
                        .HasColumnType("integer")
                        .HasColumnName("gemini_api_calls_today");

                    b.Property<long>("GeminiTokensUsedTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("gemini_tokens_used_total");

                    b.Property<DateTime>("MessagesCountResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("messages_count_reset_at");

                    b.Property<int>("MessagesToday")
                        .HasColumnType("integer")
                        .HasColumnName("messages_today");

                    b.Property<int>("PersonasCount")
                        .HasColumnType("integer")
                        .HasColumnName("personas_count");

                    b.Property<long>("StorageUsedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_used_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_usage_trackings_user_id");

                    b.ToTable("usage_trackings");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auth_provider");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_id");

                    b.Property<string>("GooglePlayPurchaseToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("google_play_purchase_token");

                    b.Property<DateTime?>("GracePeriodEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grace_period_ends_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expires_at");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subscription_tier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_users_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_firebase_uid")
                        .HasFilter("firebase_uid IS NOT NULL");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_google_id")
                        .HasFilter("google_id IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_users_is_active");

                    b.HasIndex("SubscriptionTier")
                        .HasDatabaseName("i_x_users_subscription_tier");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityData")
                        .HasColumnType("text")
                        .HasColumnName("activity_data");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TargetId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType")
                        .HasDatabaseName("i_x_user_activities_activity_type");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_user_activities_created_at");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("i_x_user_activities_target_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_activities_user_id");

                    b.ToTable("user_activities");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UserBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("i_x_user_blocks_blocked_id");

                    b.HasIndex("BlockerId")
                        .HasDatabaseName("i_x_user_blocks_blocker_id");

                    b.HasIndex("BlockerId", "BlockedId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_blocks_blocker_id_blocked_id");

                    b.ToTable("user_blocks");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UserFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid")
                        .HasColumnName("following_id");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId")
                        .HasDatabaseName("i_x_user_follows_follower_id");

                    b.HasIndex("FollowingId")
                        .HasDatabaseName("i_x_user_follows_following_id");

                    b.HasIndex("FollowerId", "FollowingId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_follows_follower_id_following_id");

                    b.ToTable("user_follows");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_chat_messages__chat_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.Persona", "Persona")
                        .WithMany("ChatSessions")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_chat_sessions__personas_persona_id");

                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_chat_sessions__users_user_id");

                    b.Navigation("Persona");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.ContentReport", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_content_reports__users_reporter_id");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.FcmToken", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithMany("FcmTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fcm_tokens__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.KnowledgeBase", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.Persona", "Persona")
                        .WithMany("KnowledgeBases")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_knowledge_bases__personas_persona_id");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.MarketplacePersona", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.Persona", "Persona")
                        .WithOne("MarketplaceListing")
                        .HasForeignKey("AiPersona.Domain.Entities.MarketplacePersona", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_marketplace_personas__personas_persona_id");

                    b.HasOne("AiPersona.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_marketplace_personas__users_seller_id");

                    b.Navigation("Persona");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.MarketplacePurchase", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "Buyer")
                        .WithMany("MarketplacePurchases")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_marketplace_purchases__users_buyer_id");

                    b.HasOne("AiPersona.Domain.Entities.MarketplacePersona", "MarketplacePersona")
                        .WithMany("Purchases")
                        .HasForeignKey("MarketplacePersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_marketplace_purchases_marketplace_personas_marketplace_pers~");

                    b.Navigation("Buyer");

                    b.Navigation("MarketplacePersona");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.MarketplaceReview", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.MarketplacePersona", "MarketplacePersona")
                        .WithMany("Reviews")
                        .HasForeignKey("MarketplacePersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_marketplace_reviews_marketplace_personas_marketplace_person~");

                    b.HasOne("AiPersona.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_marketplace_reviews__users_reviewer_id");

                    b.Navigation("MarketplacePersona");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.MessageAttachment", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.ChatMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_message_attachments_chat_messages_message_id");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.Persona", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.Persona", "ClonedFromPersona")
                        .WithMany()
                        .HasForeignKey("ClonedFromPersonaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_personas_personas_cloned_from_persona_id");

                    b.HasOne("AiPersona.Domain.Entities.User", "Creator")
                        .WithMany("Personas")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_personas__users_creator_id");

                    b.HasOne("AiPersona.Domain.Entities.User", "OriginalCreator")
                        .WithMany()
                        .HasForeignKey("OriginalCreatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_personas__users_original_creator_id");

                    b.Navigation("ClonedFromPersona");

                    b.Navigation("Creator");

                    b.Navigation("OriginalCreator");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.PersonaFavorite", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.Persona", "Persona")
                        .WithMany("Favorites")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_persona_favorites_personas_persona_id");

                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithMany("PersonaFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_persona_favorites__users_user_id");

                    b.Navigation("Persona");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.PersonaLike", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.Persona", "Persona")
                        .WithMany("Likes")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_persona_likes_personas_persona_id");

                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithMany("PersonaLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_persona_likes__users_user_id");

                    b.Navigation("Persona");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.PersonaView", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.Persona", "Persona")
                        .WithMany("Views")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_persona_views_personas_persona_id");

                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_persona_views__users_user_id");

                    b.Navigation("Persona");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.SubscriptionEvent", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithMany("SubscriptionEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_subscription_events__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.SupportTicket", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "AssignedAgent")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_support_tickets__users_assigned_to");

                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_support_tickets__users_user_id");

                    b.Navigation("AssignedAgent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.SupportTicketMessage", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_support_ticket_messages__users_sender_id");

                    b.HasOne("AiPersona.Domain.Entities.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_support_ticket_messages_support_tickets_ticket_id");

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UploadedFile", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_uploaded_files__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UsageTracking", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithOne("UsageTracking")
                        .HasForeignKey("AiPersona.Domain.Entities.UsageTracking", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_usage_trackings__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UserActivity", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_activities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UserBlock", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "Blocked")
                        .WithMany("BlockedByUsers")
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_blocks_users_blocked_id");

                    b.HasOne("AiPersona.Domain.Entities.User", "Blocker")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_blocks_users_blocker_id");

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.UserFollow", b =>
                {
                    b.HasOne("AiPersona.Domain.Entities.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_follows_users_follower_id");

                    b.HasOne("AiPersona.Domain.Entities.User", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_follows_users_following_id");

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.ChatMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.MarketplacePersona", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.Persona", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Favorites");

                    b.Navigation("KnowledgeBases");

                    b.Navigation("Likes");

                    b.Navigation("MarketplaceListing");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AiPersona.Domain.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("BlockedByUsers");

                    b.Navigation("BlockedUsers");

                    b.Navigation("ChatSessions");

                    b.Navigation("FcmTokens");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("MarketplacePurchases");

                    b.Navigation("PersonaFavorites");

                    b.Navigation("PersonaLikes");

                    b.Navigation("Personas");

                    b.Navigation("Reports");

                    b.Navigation("SubscriptionEvents");

                    b.Navigation("SupportTickets");

                    b.Navigation("UploadedFiles");

                    b.Navigation("UsageTracking");
                });
#pragma warning restore 612, 618
        }
    }
}
